/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-west-2",
    "aws_cognito_identity_pool_id": "us-west-2:45bf872a-144c-4c13-9756-35f0774634a4",
    "aws_cognito_region": "us-west-2",
    "aws_user_pools_id": "us-west-2_jo44j6FA2",
    "aws_user_pools_web_client_id": "5juq4rcro995q0irpicn8cak8t",
    "oauth": {}
};


export default awsmobile;
